require("utils.findfiles")
require("utils.theme")
require("utils.auto_close")
require("utils.manmarks")
require("utils.recording")
require("utils.redir")
require("utils.spliter")
require("utils.misc")
require("utils.session")
require("utils.non-vim-files")
require("utils.ime")
require("utils.projects")
require("utils.tmux")
require("utils.pager")

require("utils.typos").setup()
