require("utils.findfiles")
require("utils.theme")
require("utils.auto_close")
require("utils.manmarks")
require("utils.recording")
require("utils.redir")
require("utils.spliter")
require("utils.misc")

require("utils.typos").setup()
